'use strict'
const PulpFiction = function (name) {
  this.name = name
  this.qoute = []
  this.pushQoute = function (qoute) {
    return this.qoute.push(`<span>"${qoute}"</span><span>-${this.name}</span>`)
  }
}

// Push qoutes for each movie character. I need to learn how to create a database, this is time consuming. 
export const vincent = new PulpFiction('vincent')
vincent.pushQoute('Aw, man. I shot Marvin in the face.')
vincent.pushQoute('Marvin, what do you make of all of this?')
vincent.pushQoute('Jules, did you ever hear the philosophy that once a man admits that he\'s wrong that he is immediately forgiven for all wrongdoings? Have you ever heard that?')
vincent.pushQoute('That\'s a pretty fucking good milkshake.')
vincent.pushQoute('I was washing \'em. But this shit\'s hard to get off. Maybe if I had lathered or something, I coulda done a better job.')
vincent.pushQoute('Well I didn\'t mean to do it, it was an accident!')
vincent.pushQoute('Just chill out, man! I told you it was an accident! You probably, you went over a bump or something...')
vincent.pushQoute('Would you give a guy a foot massage?')
vincent.pushQoute('So you mean I gotta stab her in te heart tree times?')
vincent.pushQoute('All right, it was a miracle. Can we go now?')
vincent.pushQoute('I don\'t watch TV.')
vincent.pushQoute('Now, if you\'ll excuse me, I\'m going to go home and have a heart attack.')
vincent.pushQoute('It\'s not the same, it\'s the same ballpark.')
vincent.pushQoute('I think it looks like a wax museum with a pulse.')
vincent.pushQoute('And how long do you intend to \'walk the earth\'?')
vincent.pushQoute('You\'re really thinking about quitting?')
vincent.pushQoute('You know what they put on French fries in Holland instead of ketchup?')
vincent.pushQoute('I\'ve seen \'em do it, man. They fuckin\' drown \'em in that shit.')
vincent.pushQoute('Bacon tastes good; pork chops taste good.')
vincent.pushQoute('We should have fucking shotguns.')
vincent.pushQoute('Ain\'t hungry.')
vincent.pushQoute('And in Paris, you can buy a beer at McDonald\'s.')
vincent.pushQoute('And you know what they call a Quarter Pounder with Cheese in Paris?')
vincent.pushQoute('Nah, man, they got the metric system. They wouldn\'t know what the fuck a Quarter Pounder is.')
vincent.pushQoute('They call it a \'Royale with cheese.\'')
vincent.pushQoute('I don\'t know, I didn\'t go in a Burger King.')
vincent.pushQoute('Yeah baby, you\'d dig it the most.')
vincent.pushQoute('I ain\'t saying it\'s right. But you\'re saying a foot massage don\'t mean nothing, and I\'m saying it does.')
vincent.pushQoute('That\'s a bold statement.')
vincent.pushQoute('Are you Jewish?')
vincent.pushQoute('Yeah, but do you consider a dog to be a filthy animal?')

export const jules = new PulpFiction('jules')
jules.pushQoute('Does he look like a bitch?')
jules.pushQoute('Why the fuck did you do that?')
jules.pushQoute('English, motherfucker! Do you speak it!')
jules.pushQoute('Shut the fuck up, fatman! This ain\'t none of your goddamn business!')
jules.pushQoute('What does Marcellus Wallace look like?')
jules.pushQoute('\'What\' ain\'t no country I ever heard of, do they speak English in \'What\'?')
jules.pushQoute('English, mother fucker, do you speak it?')
jules.pushQoute('You ever read the Bible, Brett?')
jules.pushQoute('Oh, man, I will never forgive your ass for this shit. This is some fucked-up repugnant shit')
jules.pushQoute('Get the fuck out my face with that shit! The motherfucker that said that shit never had to pick up itty-bitty pieces of skull on account of your dumb ass.')
jules.pushQoute('Normally, both your asses would be dead as fucking fried chicken, but you happen to pull this shit while I\'m in a transitional period so I don\'t wanna kill you, I wanna help you.')
jules.pushQoute('Say \'what\' again. Say \'what\' again, I dare you, I double dare you motherfucker, say what one more Goddamn time!')
jules.pushQoute('Oh I\'m sorry, did I break your concentration')
jules.pushQoute('If my answers frighten you then you should cease asking scary questions.')
jules.pushQoute('You read the bible, Ringo?')
jules.pushQoute('God came down from heaven, and stopped these mother fucking bullets.')
jules.pushQoute('I used the same fuckin\' soap you did and when I got finished, the towel didn\'t look like no goddamn Maxi-Pad!')
jules.pushQoute('Ah man, I\'ve seen some crazy-ass shit in my time but this...')
jules.pushQoute('Go on!')
jules.pushQoute('Look I\'m starting to get a little pissed off here.')
jules.pushQoute('Fuck you.')
jules.pushQoute('Sewer rat might taste like pumpkin pie but I\'d never know cuz I wouldn\'t eat te filthy motherfucker.')
jules.pushQoute('What happened here was a miracle, and I want you to fucking acknowledge it!')
jules.pushQoute('It\'s the one that says Bad Motherfucker')
jules.pushQoute('Yeah, but, you are aware that there\'s an invention called television, and on this invention they show shows, right?')
jules.pushQoute('Say bitch be cool! Tell that fuckin\' bitch to chill!')
jules.pushQoute('Chill that fuckin\' bitch out!')
jules.pushQoute('In fact what the fuck am I doing in the back!? You\'re the motherfucker that should be on brain detail!')
jules.pushQoute('Ain\'t no fuckin\' ballpark, neither.')
jules.pushQoute('Now look, maybe your method of massage differs from mine, but you know, touchin\' his wife\'s feet and stickin\' yer tongue in the holiest of holies ain\'t the same fuckin\' ballpark. It ain\'t the same league, it ain\'t even the same fuckin\' sport.')
jules.pushQoute('Then why you tryin to fuck him like a bitch?')
jules.pushQoute('Motherfucker do that shit to me, he better paralyze my ass, \'cause I\'ll kill the motherfucker, know what I\'m sayin\'?')
jules.pushQoute('We should have shotguns for this kind of deal.')
jules.pushQoute('Looks like Vincent and I caught you boys at breakfast. Sorry about that. Whatcha havin\'')
jules.pushQoute('Hamburgers! The cornerstone of any nutricious breakfast!')
jules.pushQoute('Big Kahuna Burger. That\'s the Hawaiian burger joint.')
jules.pushQoute('This is a tasty burger!')
jules.pushQoute('They don\'t call it a Quarter Pounder with Cheese?')
jules.pushQoute('\'Le Big Mac!\' What do they call a Whopper?')
jules.pushQoute('I don\'t wanna hear about no motherfuckin\' ifs. All I wanna hear from your ass is, You ain\'t got no problem, Jules. I\'m on the motherfucker. Go back in there, chill them niggers out and wait for the calvary which should be coming directly.')
jules.pushQoute('Check out the big brain on Brett! You\'re a smart motherfuckerer.')
jules.pushQoute('You, Flock-of-Seagulls, know why we\'re here?')
jules.pushQoute('I don\'t remember asking you a god damn thing!')
jules.pushQoute('My name is Pitt, and your ass ain\'t talking your way outta this shit.')
jules.pushQoute('You sending the Wolf?')
jules.pushQoute('I wouldn\'t go so far as to call a dog filthy, but they\'re definitely dirty. A dog\'s got personality. Personality goes a long way.')
jules.pushQoute('What is a miracle, Vincent?')
jules.pushQoute('I wouldn\'t go so far as to call the brother fat. He\'s got a weight problem.  What\'s the nigger gonna do, he\'s Samoan.')
jules.pushQoute('Don\'t be tellin\' me about foot massages – I\'m the foot fuckin\' master.')

export const mia = new PulpFiction('mia')
mia.pushQoute('Why do we feel it\'s necessary to yak about bullshit in order to be comfortable?')
mia.pushQoute('That\'s when you know you found somebody special. When you can just shut the fuck up for a minute, and comfortably share silence.')

export const butch = new PulpFiction('butch')
butch.pushQoute('That\'s how you\'re gonna beat \'em, Butch. They keep underestimating you.')
butch.pushQoute('Zed\'s dead, baby. Zed\'s dead.')
butch.pushQoute('It\'s a Chopper baby.')
butch.pushQoute('I meant, what now between me and you')
butch.pushQoute('So we cool?')
butch.pushQoute('Sorry, baby. I had to crash that Honda.')
butch.pushQoute('I\'m American, honey. Our names don\'t mean shit.')
butch.pushQoute('I didn\'t call you a mongoloid, I called you a retard.')
butch.pushQoute('You were looking in the mirror and you decided you want some pot?')

export const theWolf = new PulpFiction('the wolf')
theWolf.pushQoute('Because you are a character doesn\'t mean the you have character.')
theWolf.pushQoute('Now let\'s not start sucking each others dicks just yet.')
theWolf.pushQoute('Toluca Lake. That\'s thirty minutes away. I\'ll be there in ten.')
theWolf.pushQoute('I\'m Winston Wolfe. I solve problems.')
theWolf.pushQoute('Rather you than me, gentlemen. Rather you than me.')
theWolf.pushQoute('Pretty please, with sugar on top; clean the fucking car!')
theWolf.pushQoute('How about you, Jimmy? Are you an oak man?')
theWolf.pushQoute(' I think fast, I talk fast, and I need you two guys to act fast if you want to get out of this.')

export const marcellusWallace = new PulpFiction('marcellus wallace')
marcellusWallace.pushQoute(' You see, this profession is filled to the brim with unrealistic motherfuckers. Motherfuckers who thought their ass would age like wine. If you mean it turns to vinegar, it does. If you mean it gets better with age, it don\'t.')
marcellusWallace.pushQoute('Motherfucker!')
marcellusWallace.pushQoute('I\'m gonna get medevil on your ass!')
marcellusWallace.pushQoute('Fuck pride! Pride only hurts, it never helps. You fight through that shit')
marcellusWallace.pushQoute('You hear me talkin\', hillbilly boy? I ain\'t through with you by a damn sight. I\'ma get medieval on your ass.')
marcellusWallace.pushQoute('Nah, man. I\'m pretty fuckin\' far from okay.')
marcellusWallace.pushQoute('What now? I\'ll tell you what now. I\'m gonna call a couple of hard-pipe hittin\' niggas to go to work on the homes here with a pair of pliers and a blow-torch.')
marcellusWallace.pushQoute('Oh, that \'what now\'. I tell you what now between me and you. There is no \'me and you\'. Not no more.')
marcellusWallace.pushQoute('Two things: one, don\'t tell nobody about this. This shit is between me, you, and Mr. soon-to-be-living-the-rest-of-his-short-ass-life-in-agonizing-pain rapist here. It ain\'t nobody else\'s business. Two, you leave town tonight, right now, and when you gone, you stay gone, or you be gone.')
marcellusWallace.pushQoute('You lost all your L.A. privileges.')
marcellusWallace.pushQoute('Yeah, we cool.')
marcellusWallace.pushQoute(' You ain\'t got no problem, Jules. I\'m on the motherfucker. Go back in there, chill them niggers out and wait for the Wolf who should be coming directly.')

export const jimmie = new PulpFiction('jimmie')
jimmie.pushQoute('You don\'t have to tell me how good my coffee is okay, I\'m the one who buys it, I know how good it is..')
jimmie.pushQoute('Oak\'s nice.')
jimmie.pushQoute('There\'s nothing that you\'re gonna say that\'s gonna make me forget that I love my wife, is there?! ')